# NUMPY #

Numpy è una libreria creata per permettere la creazione di ***array n-dimensionali in python***, le caratteristiche principali di numpy è che questa libreria è **estremamente veloce, versatile e usata in molte altre librerie**, come infatti vedremo in seguito altre librerie sono basate su di essa per permettere di fare operazioni più veloci e avere controllo sulla memoria.

<div class="alert alert-block alert-success">
    Il motivo per cui numpy è così veloce è dovuto al fatto che è basata su un linguaggio a più basso livello che è C, come vedremo in seguito questo è possibile notarlo dalla presenza di tipi di variabili con numeri di bit definiti. 
</div>

<div class="alert alert-block alert-warning">
    Numpy dovrebbe essere già installato con anaconda, qualora però non lo fosse installatelo seguendo la lezione 1-Module. 
</div>

## Cosa sono gli array ? ##

Gli array sono un concetto informatica ispirato dalla nozione di vettori, matrici o più in generale tensori usati in geometria e matematica.
Il concetto di array è già stato introdotto indirettamente nel capitolo 1 con la definzione di strutture di dati in particolare con la definizione di liste e dizionari, per avere una visione su cosa siano questi array usiamo un immagine di numpy.

![](..\img\numpy_array.png)

Come possiamo notare dall'immagine un array 1d è equivalemente a una lista in python, il problema sorge qualora ci spostiamo in array 2d o superiori per cui non abbiamo un'istruzione diretta per la creazione di tali elementi, in tal caso facciamo ricorso alla libreria notando che numpy creerà una lista di liste legata al numero di dimensioni considerata.
Vediamo però il suo utilizzo attraverso la libreria.ù

## Creazione di array e operazioni ##

### Creazione di array ###
Per creare un array in numpy in primo passo è necessario importare la libreria dopodiché è possibile inizializzare un array decidendo se dovrà contenere zeri o uni, attenzione i valori che potreste vedere potrebbero essere valori approssimata seconda la macchina essere vicini a quelli.

In [2]:
import numpy as np
#notare bene le doppie paretesi
ones_1d = np.ones((4,)) #contiene solo 4 elementi 
zeros_1d = np.zeros((4,))
print('Array 1dimensionale contenenti uni', ones_1d)
print('Array 1dimensionale contenenti zeri', zeros_1d)

Array 1dimensionale contenenti uni [1. 1. 1. 1.]
Array 1dimensionale contenenti zeri [0. 0. 0. 0.]


Qualora volessi creare array 2D l'unica modifica che è necessaria è aggiungere il numero della seconda dimensione all'interno della doppia parentesi.

In [8]:
ones_2d = np.ones((2,3))
zeros_2d = np.zeros((2,3))
print('Array 2dimensioni contenenti uni:\n', ones_2d)
print('Array 2dimensioni contenenti zeri:\n', zeros_2d)

Array 2dimensioni contenenti uni:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array 2dimensioni contenenti zeri:
 [[0. 0. 0.]
 [0. 0. 0.]]


Come è possibile notare l'array 1d è l'analogo della lista, mentre quello 2d è una lista di liste questo poiché in python come abbiamo detto non esistono altre strutture oltre a questa per la memorizzazione di dati in maniera ordinata. 
Per quanto riguarda gli array 3d ripetiamo i procedimenti precedenti.

In [9]:
ones_3d = np.ones((4,3,2))
zeros_3d = np.zeros((4,3,2))
print('Array 3dimensioni contenenti uni:\n', ones_3d)
print('Array 3dimensioni contenenti zeri:\n', zeros_3d)

Array 3dimensioni contenenti uni:
 [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
Array 3dimensioni contenenti zeri:
 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


### Operazioni su array ###
Su questi array è possibile effettuare delle operazioni come se fossero delle variabili e molte altre.
#### Addizione ####
Per l'operazione di somma tra due array a noi basta usare `+` oppure `np.add`.

In [10]:
print(ones_1d+ones_1d)

[2. 2. 2. 2.]


In [11]:
print(np.add(ones_1d, ones_1d))

[2. 2. 2. 2.]


#### Sottrazione ####
Per l'operazione di differenza tra due array a noi basta usare `-` oppure `np.substract`.

In [12]:
print(ones_2d - ones_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


#### Moltiplicazione ####
Per l'operazione di moltiplicazione tra due array a noi basta usare `*` oppure `np.multiply`.

In [13]:
print(ones_2d * zeros_2d)

[[0. 0. 0.]
 [0. 0. 0.]]


#### Divisione ####
Per l'operazione di divisione tra due array a noi basta usare `/` oppure `np.divide`.

In [15]:
print(ones_2d / 2)

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]


<div class="alert alert-block alert-success">
    Notare bene che l'ultima operazione che ho fatto non è tra due array, il motivo per cui funzione è dovuto al broadcasting che manipola gli array in maniera tale da avere la stessa dimensione, fare riferimento a questo <a href="https://www.tutorialspoint.com/numpy/numpy_broadcast.htm">link</a>.
</div>

Sarebbero presente molte altre operazioni che sarebbero troppo lunghe da elencare, per avere un quadro generale di tutto ciò potete consultare questo __[cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)__, mentre se aveste dubbi potete consultare la __[documentazione](https://numpy.org/doc/stable/index.html)__.